#!/bin/bash

EXPECTED_ARGS=3
E_BADARGS=65
MYSQL=`which mysql`

$MYSQL -uroot -p<<MYSQL_SCRIPT
CREATE DATABASE IF NOT EXISTS $1;
CREATE USER '$2'@'localhost' IDENTIFIED BY '$3';
GRANT ALL PRIVILEGES ON $1.* TO $2@localhost;
FLUSH PRIVILEGES;
MYSQL_SCRIPT

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: $0 dbname dbuser dbpass"
  exit $E_BADARGS
fi

echo "MySQL user and DB created."
echo "Database:   $1"
echo "Username:   $2"
echo "Password:   $3"
sleep 1
